### ISSUE TITLE
Error: Failed to reset Zulu repository

### ISSUE THREAD

**Issue by sbibauw** [zulu-zsh/zulu#108]
When installing Zulu for the first time, I got this error in the installation process:

    [...]
    ✔ Build script complete
    HEAD is now at b91f492ddb96 Ensure default branch is used unless specified
    Failed to reset Zulu repository

And every time I open a Terminal window/tab, I get the same error.
This said, when browsing and checking the git status of `/core/` and `/index/` in the ZULU_DIR, both seem to be correctly synced to `upstream master`.

**Comment by sbibauw** [comment]
Not solved though...

**Comment by molovo** [comment]
@sbibauw Sorry, stalebot killed this. Reopening it so I don't forget about it
