### ISSUE TITLE
Package Index types

### ISSUE THREAD

**Issue by rolling-space** [zulu-zsh/zulu#28]
Hi there, wishes for happy holidays!

I have noticed that the [completions](https://github.com/zulu-zsh/index/blob/master/packages/completions) index references a 'completion' type.

Is this functionality of a private nature and thus didn't make it to the [index docs](https://github.com/zulu-zsh/index)?

**Comment by molovo** [comment]
It doesn't contribute any functionality at the moment. The only real functionality I had planned was to automatically enable themes after install, but other than that there's no real relevance at the moment. The key isn't required in the JSON for the package to be installable, and if that changes it's fairly trivial to update the entries for any packages that are missing types.

**Comment by petrosp** [comment]
Ok, that has been cleared, closing. Thanks!
