### ISSUE TITLE
zsh-syntax-highlighting and zsh-history-substring-search

### ISSUE THREAD

**Issue by rolling-space** [zulu-zsh/zulu#29]
Hi,

I was wondering whether the `_zulu_init_setup_history` function in the `init` command is respecting the order that `zsh-history-substring-search` is sourced, in case the `zsh-syntax-highlighting` package is also installed.

I came down to this sort of investigation after struggling with the `zsh-history-substring-search` itself: To my understanding, if you have installed it, it will be loaded with the rest of the packages _after_ the `_zulu_init_setup_history` -- [which will exit](https://github.com/zulu-zsh/zulu/blob/master/commands/init#L175) unless the widget is defined. However, this will be defined during the package load.  I had to source the `zsh-history-substring-search` before line 175. Have you noticed that or am I totally losing it?

In any case, you have build a very comprehensive framework here, lightweight and pretty much extensible. 

Thanks! Happy new year!

**Comment by molovo** [comment]
I don't use the `zsh-history-substring-search` plugin, so hadn't noticed an issue. I expect it can be solved by shuffling the order of the initialisation script. I'll have a play and see if I can recreate it.

And thanks, glad to know you're getting some use of it.

**Comment by rolling-space** [comment]
Indeed, I reshuffled the init order and placed ` _zulu_init_setup_history` after `_zulu_load_packages` to ensure that the widget is sourced and thus found:
```
  # Set up the environment
  _zulu_init_setup_key_bindings
  _zulu_init_setup_completion

  # Load installed packages
  _zulu_load_packages

 _zulu_init_setup_history
  # Load aliases
  zulu alias load
``` 
Now `syntax-highlighting` works, but `substring-search` partially as it does not respect the `HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND` setting in the [init](https://github.com/zulu-zsh/zulu/blob/master/commands/init#L191) command.

Seems that there is some contradiction on the instructions of both `substring-search` and `syntax-highlighting` plugins: [Instructions](https://github.com/zsh-users/zsh-syntax-highlighting#why-must-zsh-syntax-highlightingzsh-be-sourced-at-the-end-of-the-zshrc-file) of the latter claim that the former should be placed first, while the former claims to be [sourced as the very last plugin](https://github.com/zsh-users/zsh-history-substring-search#usage).

In any case, I tried to also install `syntax-highlighting` via `brew` and the issue persists still, so not tied in any way with `zulu`

I am not sure about any subsequent implications of the init order change, it seems though that neither [zim](https://github.com/Eriner/zim/blob/master/templates/zimrc#L15) nor [prezto](https://github.com/zsh-users/prezto/blob/master/runcoms/zpreztorc#L34-L35) agree on a common order.

**Comment by molovo** [comment]
I tried making the change you mention above, but unfortunately it hasn't had the desired effect for me; I can't get any of the keybindings that are setup on init to fire the widget, but the `history-substring-search-{up,down}` methods are both loaded into the environment - the same behaviour I had before the change.

I've not tried zim, but the majority of the `_zulu_init_setup_history` function was borrowed from Prezto, and I used to use the plugin when I used that framework, so there must be a way to get it working. I need to diff my code against Prezto's history module to try and remember what I've changed and see if that's the issue - I have an inkling it may actually be in the way that the keymap is set up in `_zulu_init_setup_key_bindings`.

Side note: There's a slight issue with Zulu's architecture, in that plugins are loaded in alphabetical order, as I simply source the entire contents of the directory at `~/.zulu/init` within the `_zulu_load_packages` function. If a package particularly needs to be sourced at the beginning or the end, that can be done by modifying the packages index entry to change the name of the linked file to something that will appear where needed in the order, something like `1.package-name` perhaps. That's a little unwieldy though, so any ideas for a better way are welcome.

**Comment by molovo** [comment]
Think I've found the issue - the widgets need to be registered with ZLE before the keybindings are registered. The highlighting works for me as well.

Can be fixed by adding these lines immediately after line 185 of `~/.zulu/core/commands/init`:

```shell
zle -N history-substring-search-up
zle -N history-substring-search-down
```

Does that fix the issue for you?

**Comment by rolling-space** [comment]
This doesn't work for me :( 

However, if you register them just before line 178 it does. :)

Nevertheless even in that case, the colors for `substring-search` are not displaying. Evidently, `substring-search` needs to be loaded last.

I managed to have that resolved, by splitting `_zulu_init_setup_history` function into two functions and adding the last after the package loading. I sent a PR -- even though a bit prematurely maybe.

**Comment by rolling-space** [comment]
I am actually wondering at `init#L184`:
```

    # Source module files.
    [[ -f "$base/init/zsh-history-substring-search.zsh" ]] || return 1

```
The above does not actually sourcing the file, just checks existence and exits if false.

Is this the real intention?

**Comment by molovo** [comment]
It is the intention, yes. The reason for that, is purely to check for the existence of the plugin. If the package is installed with zulu, it will be already have been sourced during the `_zulu_load_packages` step.

**Comment by molovo** [comment]
What OS/ZSH version are you using? The colours are appearing correctly on my machine (Mac OS 10.12, ZSH 5.3)

**Comment by rolling-space** [comment]
```
❯ zsh --version
zsh 5.3.1 (x86_64-apple-darwin15.6.0)
```
macOS 10.11.6

**Comment by rolling-space** [comment]
Well, I am not really taking out the possibility my packages to have messed up the colors. I have published them all at [https://github.com/rolling-space](https://github.com/rolling-space).

The current `master` -- since 20 days ago -- does not load the `substring-search` before, but it is loaded after, during the package load:
```
  # Set up the environment
  _zulu_init_setup_key_bindings
  _zulu_init_setup_history
  _zulu_init_setup_completion

  # Load installed packages
  _zulu_load_packages
```

**Comment by molovo** [comment]
Yeah, that's right. The package were originally loaded first, but that was moved to later in a previous commit. I pushed PR #30 this afternoon, which performs the history setup after the packages are loaded, and binds the widgets to ZLE.

What is the value of `HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND` on your system?

**Comment by rolling-space** [comment]
Currently this:
`HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=blue,fg=white,bold'`

**Comment by rolling-space** [comment]
My `init` is currently identical to the one I PR'd earlier. All colors are visible with this `init`, even the original ones.

**Comment by molovo** [comment]
Your fix would source the script a second time though, as it would already be sourced when `_zulu_load_packages` is run. That shouldn't be necessary, and in fact, looking at it again, checking for the existence of the file isn't really necessary since we're checking for the existence of the widget directly below it which should be enough.

I'm wondering if there's another package interfering with your highlighting. Can you please post the output of `zulu list --all`?

**Comment by molovo** [comment]
Also, where are you setting the value of `$HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND`?

**Comment by rolling-space** [comment]
Yes, both are quite true indeed! This can be a trigger to contemplate on a load deferring system, which could be implemented using 'before' and 'after' keys in the `json` index files.

```
  agnoster
✔ alias-tips
  almostontop
  ansiweather
✔ archive
  async
✔ autosuggestions
  cdbk
✔ color
✔ command-not-found
✔ completions
  crystal
✔ directory
  dnf
  dpkg
  fasd
  filthy
✔ fzf
  fzf-marks
  git
✔ git-extra-commands
  gitignore
  gitio
  gnu-utility
✔ history-substring-search
  history-sync
  insert-sudo
✔ intelf-pure
✔ k
  load-graph
  lumberjack
✔ nvm-auto-use
  pretty-time
  pure
  rbenv
✔ revolver
✔ snoopy-pure-theme
✔ snoopy-theme
✔ syntax-highlighting
  tipz
✔ z
✔ z-cd
  zim-homebrew
  zim-mashup
  zim-osx
  zim-utility
✔ zulu-docker
✔ zulu-git
✔ zulu-homebrew
✔ zulu-node
✔ zulu-osx
✔ zulu-rake-fast
✔ zulu-rbenv
✔ zulu-utility
✔ zulu-yarn
  zunit
```

**Comment by rolling-space** [comment]
I set the  color at `_zulu_init_setup_history`

**Comment by rolling-space** [comment]
Ok, I applied the changes of the `fix_histrory_setup` branch and works! Both history and color!

**Comment by molovo** [comment]
Ah! Brilliant. That's good. I'll get it merged

**Comment by molovo** [comment]
@rolling-space Thanks very much for your help debugging, it's appreciated. Is #31 still needed now, or can I close it?

**Comment by rolling-space** [comment]
@molovo, it was a pleasure! [#31](https://github.com/zulu-zsh/zulu/pull/31) may be epically closed indeed! 

Thanks for taking the time.
