### ISSUE TITLE
can't keep theme setting after zulu upgrade

### ISSUE THREAD

**Issue by dreamfliper** [zulu-zsh/zulu#59]
before running `zulu upgrade`, I was using agnoster as my theme. however, zulu change the theme to default theme after `zulu upgrade`.
this also reminds me there's no auto-completion when I pressing `tab` after `zulu theme`

**Comment by molovo** [comment]
Thanks for the bug report. I think I know what's causing the theme to change, I'll get a fix out ASAP.

The autocompletion for themes has never been implemented, but I'll try and get that included in v1.2.0

**Comment by molovo** [comment]
The fix is in master now, so if you run a `self-update` you shouldn't have the same issue again.
