### ISSUE TITLE
install packages from git that are not in index

### ISSUE THREAD

**Issue by rrevanth** [zulu-zsh/zulu#83]
Is there an option to install package from git directly rather than adding it to index before?

**Comment by molovo** [comment]
There isn't at the moment, and it's not something I had planned, but I'd be willing to consider PRs that bear the following in mind:

I chose to make zulu work with an index simply to make it easier for end users - packages should always install first time without any additional configuration.

Installing directly from github would be useful for users with more knowledge of zsh, but that's not really who zulu is aimed at, and I want to avoid making the install options too verbose and confusing for that reason. I hope that makes sense.

If you'd rather not add to the index yourself, by all means create an issue at https://github.com/zulu-zsh/index suggesting any packages, and I'll add then to the index when I have time

**Comment by rrevanth** [comment]
Ok. Thank you! I just wanted to know if i'm missing something 😄  

I wanted to install my own customized versions of plugins to an index so I can install them directly, they are not to be added to generalized index. Hence, I asked if packages can be installed directly 👍

**Comment by molovo** [comment]
Ah, I see. Well you have two options which *should* work:

1. Make the modifications to packages or add new ones locally. Zulu should respect local changes - that's not been tested extensively though, so be warned.
2. Fork the index repository and edit the origin in `~/.zulu/index` and maintain your own index, but obviously you'll miss out on updates to the main index.

Let me know if you have any other ideas for ways I can make this easier.
