### ISSUE TITLE
unlink not happening while uninstalling

### ISSUE THREAD

**Issue by rrevanth** [zulu-zsh/zulu#85]
whenever I uninstall a package, the corresponding init file is not unlinking itself.

I had to manually run the unlink command initially and then uninstall the package or delete the file manually.

I see the code for unlinking is there, not sure why not happening though

**Comment by molovo** [comment]
Is this happening for all packages, or just one in particular?

**Comment by molovo** [comment]
Is this happening for all packages, or just one in particular?

**Comment by molovo** [comment]
Also, what OS and ZSH version are you running?

**Comment by rrevanth** [comment]
Mac OS 10.12.4 and ZSH : 5.3.1

It's happening to all the packages on my system

**Comment by molovo** [comment]
OK, thanks very much for reporting. I'm unlikely to get to it within the next week as I'm on vacation, but I'll try and get a fix sorted next weekend

**Comment by molovo** [comment]
Still looking into this. I ran some tests last night on OSX and Ubuntu and wasn't able to recreate the issue.

@rrevanth Could you please post the contents of `~/.config/zulu/packages`, and let me know if you have any aliases defined for `ls`, `grep`, `awk` or `xargs` and what they are?

**Comment by molovo** [comment]
@rrevanth are you still having issues with this? If so, could you please answer the above question?

**Comment by molovo** [comment]
Since there's been no answer, and I've been unable to recreate the issue, I'm going to close it for now so it doesn't hold up v1.4.0
